services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: bp_sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQLSERVER_PASSWORD:-YourStrong!Passw0rd}
    ports:
      - "${SQLSERVER_PORT:-1433}:1433"
    volumes:
      - ./data/raw/adventureworks:/var/opt/mssql/backup
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SQLSERVER_PASSWORD:-YourStrong!Passw0rd} -Q 'SELECT 1' || exit 1"]

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-analytics_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: